### ISSUE TITLE
Change folder default generate

### ISSUE THREAD

**Issue by phuongdm1987** [laracademy/ModelGenerator#5]
I want change folder default generate

ex: form /Projects/lab/app/User.php to /Projects/lab/app/Folder/User.php

please help, thank you!

**Comment by laracademy** [comment]
Nice suggestion.

I will be working on that shortly, in the mean time you should star this new repo, as this one will be discontinued to move everything into a "generator" so that under one package there can be a bunch of "generators"

(https://github.com/laracademy/generators)

**Comment by laracademy** [comment]
@phuongdm1987 This feature you can find in the new package which is located at the follow url: https://packagist.org/packages/laracademy/generators

The reason for the change of packages is because I have had multiple requests for different generators and thought it would be better if they were all under one roof.
